### ISSUE TITLE
Don't translate the special markdown tags

### ISSUE THREAD

**Issue by wilzbach** [dlang-tour/spanish#17]
Compare:

https://tour.dlang.org/tour/es/basics/basic-types

with:

https://tour.dlang.org/tour/en/basics/basic-types

In short: `## {SourceCode}` is needed for the detection to work.
In theory that part could be localized and read from the language YAML (see e.g. https://github.com/dlang-tour/core/blob/master/source/contentprovider.d#L29 and https://github.com/dlang-tour/core/blob/master/source/translator.d), but at the moment this isn't supported.

**Comment by csantander** [comment]
I checked all the .md files and I didn't see `## {SourceCode}` translated in any of them. I only saw a couple that had an `incomplete` attribute, but I don't think that's what you're referring to. I also didn't notice any difference between the English and Spanish versions. Can you pinpoint where you're seeing an issue?

**Comment by wilzbach** [comment]
Oh sorry it looks like it was a temporary bug with my browser cache. Sorry for the noise and confusion and thanks a lot for the hard work!
